info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-27T02:05:19.211Z"}
info: Connected to the database. {"timestamp":"2022-07-27T02:05:19.270Z"}
error: 
    status - 500 
    message - JsonWebTokenError: jwt malformed
    at Object.verify (C:\CFP_170\NodeJs\FundooNotes\node_modules\jsonwebtoken\verify.js:63:17)
    at _callee2$ (C:\CFP_170\NodeJs\FundooNotes\src\middlewares\/auth.middleware.js:51:30)
    at tryCatch (C:\CFP_170\NodeJs\FundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\CFP_170\NodeJs\FundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\CFP_170\NodeJs\FundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\CFP_170\NodeJs\FundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\CFP_170\NodeJs\FundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\CFP_170\NodeJs\FundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at C:\CFP_170\NodeJs\FundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at resetAuth (C:\CFP_170\NodeJs\FundooNotes\src\middlewares\/auth.middleware.js:41:23)
    at Layer.handle [as handle_request] (C:\CFP_170\NodeJs\FundooNotes\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\CFP_170\NodeJs\FundooNotes\node_modules\express\lib\router\route.js:144:13)
    at Route.dispatch (C:\CFP_170\NodeJs\FundooNotes\node_modules\express\lib\router\route.js:114:3)
    at Layer.handle [as handle_request] (C:\CFP_170\NodeJs\FundooNotes\node_modules\express\lib\router\layer.js:95:5)
    at C:\CFP_170\NodeJs\FundooNotes\node_modules\express\lib\router\index.js:284:15 
    url - /api/v1/users/user 
    method - POST 
    IP - ::1
   {"timestamp":"2022-07-27T02:06:33.714Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-27T02:09:31.969Z"}
info: Connected to the database. {"timestamp":"2022-07-27T02:09:32.034Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-27T02:09:52.095Z"}
info: Connected to the database. {"timestamp":"2022-07-27T02:09:52.124Z"}
error: 
    status - 500 
    message - JsonWebTokenError: jwt malformed
    at Object.verify (C:\CFP_170\NodeJs\FundooNotes\node_modules\jsonwebtoken\verify.js:63:17)
    at _callee2$ (C:\CFP_170\NodeJs\FundooNotes\src\middlewares\/auth.middleware.js:51:30)
    at tryCatch (C:\CFP_170\NodeJs\FundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\CFP_170\NodeJs\FundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\CFP_170\NodeJs\FundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\CFP_170\NodeJs\FundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\CFP_170\NodeJs\FundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\CFP_170\NodeJs\FundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at C:\CFP_170\NodeJs\FundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at resetAuth (C:\CFP_170\NodeJs\FundooNotes\src\middlewares\/auth.middleware.js:41:23)
    at Layer.handle [as handle_request] (C:\CFP_170\NodeJs\FundooNotes\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\CFP_170\NodeJs\FundooNotes\node_modules\express\lib\router\route.js:144:13)
    at Route.dispatch (C:\CFP_170\NodeJs\FundooNotes\node_modules\express\lib\router\route.js:114:3)
    at Layer.handle [as handle_request] (C:\CFP_170\NodeJs\FundooNotes\node_modules\express\lib\router\layer.js:95:5)
    at C:\CFP_170\NodeJs\FundooNotes\node_modules\express\lib\router\index.js:284:15 
    url - /api/v1/users/users 
    method - POST 
    IP - ::1
   {"timestamp":"2022-07-27T02:10:42.282Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-27T02:38:55.327Z"}
info: Connected to the database. {"timestamp":"2022-07-27T02:38:55.443Z"}
error: 
    status - 500 
    message - JsonWebTokenError: jwt malformed
    at Object.verify (C:\CFP_170\NodeJs\FundooNotes\node_modules\jsonwebtoken\verify.js:63:17)
    at _callee2$ (C:\CFP_170\NodeJs\FundooNotes\src\middlewares\/auth.middleware.js:51:30)
    at tryCatch (C:\CFP_170\NodeJs\FundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\CFP_170\NodeJs\FundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\CFP_170\NodeJs\FundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\CFP_170\NodeJs\FundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\CFP_170\NodeJs\FundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\CFP_170\NodeJs\FundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at C:\CFP_170\NodeJs\FundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at resetAuth (C:\CFP_170\NodeJs\FundooNotes\src\middlewares\/auth.middleware.js:41:23)
    at Layer.handle [as handle_request] (C:\CFP_170\NodeJs\FundooNotes\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\CFP_170\NodeJs\FundooNotes\node_modules\express\lib\router\route.js:144:13)
    at Route.dispatch (C:\CFP_170\NodeJs\FundooNotes\node_modules\express\lib\router\route.js:114:3)
    at Layer.handle [as handle_request] (C:\CFP_170\NodeJs\FundooNotes\node_modules\express\lib\router\layer.js:95:5)
    at C:\CFP_170\NodeJs\FundooNotes\node_modules\express\lib\router\index.js:284:15 
    url - /api/v1/users/users 
    method - POST 
    IP - ::1
   {"timestamp":"2022-07-27T02:39:42.196Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-27T02:43:09.746Z"}
info: Connected to the database. {"timestamp":"2022-07-27T02:43:09.811Z"}
error: 
      status - 400
      message - Authorization token is required 
      url - /api/v1/notes 
      method - POST 
      IP - ::1
     {"timestamp":"2022-07-27T07:46:50.214Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-27T07:50:45.985Z"}
info: Connected to the database. {"timestamp":"2022-07-27T07:50:46.036Z"}
error: 
      status - 400
      message - Authorization token is required 
      url - /api/v1/notes 
      method - POST 
      IP - ::1
     {"timestamp":"2022-07-27T07:51:20.143Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-27T08:10:00.745Z"}
info: Connected to the database. {"timestamp":"2022-07-27T08:10:00.789Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-27T10:38:13.695Z"}
info: Connected to the database. {"timestamp":"2022-07-27T10:38:13.745Z"}
error: 
      status - 400
      message - Authorization token is required 
      url - /api/v1/notes 
      method - POST 
      IP - ::1
     {"timestamp":"2022-07-27T11:47:40.336Z"}
error: 
      status - 400
      message - Authorization token is required 
      url - /api/v1/notes/ 
      method - GET 
      IP - ::1
     {"timestamp":"2022-07-27T11:49:56.314Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-27T11:50:41.931Z"}
info: Connected to the database. {"timestamp":"2022-07-27T11:50:41.981Z"}
error: 
      status - 400
      message - Authorization token is required 
      url - /api/v1/notes/ 
      method - GET 
      IP - ::1
     {"timestamp":"2022-07-27T11:50:49.347Z"}
error: 
      status - 400
      message - Authorization token is required 
      url - /api/v1/notes/ 
      method - GET 
      IP - ::1
     {"timestamp":"2022-07-27T11:50:57.635Z"}
error: 
      status - 400
      message - Authorization token is required 
      url - /api/v1/notes 
      method - GET 
      IP - ::1
     {"timestamp":"2022-07-27T11:51:23.220Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-27T11:53:56.212Z"}
info: Connected to the database. {"timestamp":"2022-07-27T11:53:56.242Z"}
error: 
      status - 400
      message - Authorization token is required 
      url - /api/v1/notes 
      method - GET 
      IP - ::1
     {"timestamp":"2022-07-27T11:54:03.839Z"}
error: 
      status - 400
      message - Authorization token is required 
      url - /api/v1/notes/ 
      method - GET 
      IP - ::1
     {"timestamp":"2022-07-27T11:54:20.207Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-27T11:59:25.148Z"}
info: Connected to the database. {"timestamp":"2022-07-27T11:59:25.201Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-27T12:03:16.144Z"}
info: Connected to the database. {"timestamp":"2022-07-27T12:03:16.184Z"}
error: 
      status - 400
      message - Authorization token is required 
      url - /api/v1/notes/%7B_id%7D 
      method - GET 
      IP - ::1
     {"timestamp":"2022-07-27T12:24:16.366Z"}
error: 
    status - 500 
    message - JsonWebTokenError: jwt must be provided
    at Object.verify (C:\CFP_170\NodeJs\FundooNotes\node_modules\jsonwebtoken\verify.js:53:17)
    at _callee$ (C:\CFP_170\NodeJs\FundooNotes\src\middlewares\/auth.middleware.js:24:28)
    at tryCatch (C:\CFP_170\NodeJs\FundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\CFP_170\NodeJs\FundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\CFP_170\NodeJs\FundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\CFP_170\NodeJs\FundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\CFP_170\NodeJs\FundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\CFP_170\NodeJs\FundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at C:\CFP_170\NodeJs\FundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at userAuth (C:\CFP_170\NodeJs\FundooNotes\src\middlewares\/auth.middleware.js:12:22)
    at Layer.handle [as handle_request] (C:\CFP_170\NodeJs\FundooNotes\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\CFP_170\NodeJs\FundooNotes\node_modules\express\lib\router\route.js:144:13)
    at Route.dispatch (C:\CFP_170\NodeJs\FundooNotes\node_modules\express\lib\router\route.js:114:3)
    at Layer.handle [as handle_request] (C:\CFP_170\NodeJs\FundooNotes\node_modules\express\lib\router\layer.js:95:5)
    at C:\CFP_170\NodeJs\FundooNotes\node_modules\express\lib\router\index.js:284:15 
    url - /api/v1/notes/%7B_id%7D 
    method - GET 
    IP - ::1
   {"timestamp":"2022-07-27T12:25:08.242Z"}
error: 
      status - 400
      message - Authorization token is required 
      url - /api/v1/notes/%7B_id%7D 
      method - GET 
      IP - ::1
     {"timestamp":"2022-07-27T12:42:14.788Z"}
error: 
    status - 500 
    message - JsonWebTokenError: jwt must be provided
    at Object.verify (C:\CFP_170\NodeJs\FundooNotes\node_modules\jsonwebtoken\verify.js:53:17)
    at _callee$ (C:\CFP_170\NodeJs\FundooNotes\src\middlewares\/auth.middleware.js:24:28)
    at tryCatch (C:\CFP_170\NodeJs\FundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\CFP_170\NodeJs\FundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\CFP_170\NodeJs\FundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\CFP_170\NodeJs\FundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\CFP_170\NodeJs\FundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\CFP_170\NodeJs\FundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at C:\CFP_170\NodeJs\FundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at userAuth (C:\CFP_170\NodeJs\FundooNotes\src\middlewares\/auth.middleware.js:12:22)
    at Layer.handle [as handle_request] (C:\CFP_170\NodeJs\FundooNotes\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\CFP_170\NodeJs\FundooNotes\node_modules\express\lib\router\route.js:144:13)
    at Route.dispatch (C:\CFP_170\NodeJs\FundooNotes\node_modules\express\lib\router\route.js:114:3)
    at Layer.handle [as handle_request] (C:\CFP_170\NodeJs\FundooNotes\node_modules\express\lib\router\layer.js:95:5)
    at C:\CFP_170\NodeJs\FundooNotes\node_modules\express\lib\router\index.js:284:15 
    url - /api/v1/notes/%7B_id%7D 
    method - GET 
    IP - ::1
   {"timestamp":"2022-07-27T12:43:03.049Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-27T15:55:40.292Z"}
info: Connected to the database. {"timestamp":"2022-07-27T15:55:40.330Z"}
error: 
    status - 500 
    message - CastError: Cast to ObjectId failed for value "{ _id: '{_id}', UserId: 'manu@gmail.com' }" (type Object) at path "_id" for model "Note"
    at model.Query.exec (C:\CFP_170\NodeJs\FundooNotes\node_modules\mongoose\lib\query.js:4498:21)
    at model.Query.Query.then (C:\CFP_170\NodeJs\FundooNotes\node_modules\mongoose\lib\query.js:4592:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/notes/%7B_id%7D 
    method - GET 
    IP - ::1
   {"timestamp":"2022-07-27T16:24:38.175Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-27T16:52:35.096Z"}
info: Connected to the database. {"timestamp":"2022-07-27T16:52:35.154Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-27T16:57:17.244Z"}
info: Connected to the database. {"timestamp":"2022-07-27T16:57:17.297Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-27T17:00:10.245Z"}
info: Connected to the database. {"timestamp":"2022-07-27T17:00:10.291Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-27T17:44:59.606Z"}
info: Connected to the database. {"timestamp":"2022-07-27T17:44:59.644Z"}
error: 
    status - 500 
    message - CastError: Cast to ObjectId failed for value "{ _id: '{_id}', UserId: 'manu@gmail.com' }" (type Object) at path "_id" for model "Note"
    at model.Query.exec (C:\CFP_170\NodeJs\FundooNotes\node_modules\mongoose\lib\query.js:4498:21)
    at model.Query.Query.then (C:\CFP_170\NodeJs\FundooNotes\node_modules\mongoose\lib\query.js:4592:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/notes/%7B_id%7D 
    method - GET 
    IP - ::1
   {"timestamp":"2022-07-27T17:46:08.429Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-27T17:47:30.223Z"}
info: Connected to the database. {"timestamp":"2022-07-27T17:47:30.261Z"}
error: 
    status - 500 
    message - CastError: Cast to ObjectId failed for value "{ _id: '{_id}', UserId: 'pujith008@gmail.com' }" (type Object) at path "_id" for model "Note"
    at model.Query.exec (C:\CFP_170\NodeJs\FundooNotes\node_modules\mongoose\lib\query.js:4498:21)
    at model.Query.Query.then (C:\CFP_170\NodeJs\FundooNotes\node_modules\mongoose\lib\query.js:4592:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/notes/%7B_id%7D 
    method - GET 
    IP - ::1
   {"timestamp":"2022-07-27T17:48:42.802Z"}
